# Generated by Django 2.1.7 on 2019-04-07 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myexam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.IntegerField(default=1),
        ),
    ]
